### ISSUE TITLE
Execution failed

### ISSUE THREAD

**Issue by epaew** [epaew/eslint-plugin-filenames-simple#26]
## Environment
* Node.js version: 12.16.3
* ESLint version: 7.1.0
* Plugin version: 0.3.0

### Expected behavior
Run ESLint and then finish successfully.

### Actual behavior
Failed to run ESLint.
```
$ eslint .

Oops! Something went wrong! :(

ESLint: 7.1.0

TypeError: declarationParser(...) is not a function or its return value is not iterable
Occurred while linting /home/epaew/workspace/eslint-plugin-filenames-simple/types.ts:1
...
```

### Minimum code of lint target to reproduce the bug
* types.ts
    ```
    export type types = {}
    ```

### ESLint config
* .eslintrc.yaml
    ```
    ---
    root: true
    env:
      es2017: true
      node: true
    extends:
      - plugin:filenames-simple/recommended
    parser: '@typescript-eslint/parser'
    parserOptions:
      ecmaVersion: 2019
      sourceType: module
    ```
